// <auto-generated />
using LinguaCorp.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LinguaCorp.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251107175137_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("LinguaCorp.API.Models.Phrase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TranslatedText")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Phrases");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Language = "en",
                            OriginalText = "Hello",
                            TranslatedText = "Olá"
                        },
                        new
                        {
                            Id = 2,
                            Language = "en",
                            OriginalText = "Thank you",
                            TranslatedText = "Obrigado"
                        },
                        new
                        {
                            Id = 3,
                            Language = "en",
                            OriginalText = "Good morning",
                            TranslatedText = "Bom dia"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
